reaper.SetMouseModifier('Media item left drag', 0, 'Marquee select items and time')
reaper.SetMouseModifier('Media item left drag', 1, 'Marquee select items and time')
reaper.SetMouseModifier('Media item left drag', 2, 'Move item ignoring time selection, enabling ripple edit for all tracks')
reaper.SetMouseModifier('Media item left drag', 3, 'Move item ignoring time selection, enabling ripple edit for this track')
reaper.SetMouseModifier('Media item left drag', 4, 'Copy item')
reaper.SetMouseModifier('Media item left drag', 5, 'Adjust take pitch (fine)')
reaper.SetMouseModifier('Media item left drag', 6, 'Move item')
reaper.SetMouseModifier('Media item left drag', 7, 'Copy item, pooling MIDI source data')
reaper.SetMouseModifier('Media item left drag', 8, 'Move item vertically')
reaper.SetMouseModifier('Media item left drag', 9, 'Adjust item volume')
reaper.SetMouseModifier('Media item left drag', 10, '-1')
reaper.SetMouseModifier('Media item left drag', 11, '-1')
reaper.SetMouseModifier('Media item left drag', 12, 'Copy item vertically')
reaper.SetMouseModifier('Media item left drag', 13, 'Adjust take pitch (semitones)')
reaper.SetMouseModifier('Media item left drag', 14, '-1')
reaper.SetMouseModifier('Media item left drag', 15, '-1')
reaper.SetMouseModifier('Media item bottom half left drag', 0, 'Marquee select items and time')
reaper.SetMouseModifier('Media item bottom half left drag', 1, 'Marquee select items and time')
reaper.SetMouseModifier('Media item bottom half left drag', 2, 'Move item ignoring time selection, enabling ripple edit for all tracks')
reaper.SetMouseModifier('Media item bottom half left drag', 3, 'Move item ignoring time selection, enabling ripple edit for this track')
reaper.SetMouseModifier('Media item bottom half left drag', 4, 'Copy item')
reaper.SetMouseModifier('Media item bottom half left drag', 5, 'Adjust take pitch (fine)')
reaper.SetMouseModifier('Media item bottom half left drag', 6, 'Move item')
reaper.SetMouseModifier('Media item bottom half left drag', 7, 'Copy item, pooling MIDI source data')
reaper.SetMouseModifier('Media item bottom half left drag', 8, 'Move item vertically')
reaper.SetMouseModifier('Media item bottom half left drag', 9, 'Adjust item volume')
reaper.SetMouseModifier('Media item bottom half left drag', 10, '-1')
reaper.SetMouseModifier('Media item bottom half left drag', 11, '-1')
reaper.SetMouseModifier('Media item bottom half left drag', 12, 'Copy item vertically')
reaper.SetMouseModifier('Media item bottom half left drag', 13, 'Adjust take pitch (semitones)')
reaper.SetMouseModifier('Media item bottom half left drag', 14, '-1')
reaper.SetMouseModifier('Media item bottom half left drag', 15, '-1')
reaper.SetMouseModifier("Media item edge left drag", 0, "0")
reaper.SetMouseModifier("Media item edge left drag", 1, "0")
reaper.SetMouseModifier("Media item edge left drag", 2, "0")
reaper.SetMouseModifier("Media item edge left drag", 3, "0")
reaper.SetMouseModifier("Media item edge left drag", 4, "Stretch item (relative edge edit)")
reaper.SetMouseModifier("Media item edge left drag", 5, "Stretch item ignoring snap (relative edge edit)")
reaper.SetMouseModifier("Media item edge left drag", 6, "Stretch item ignoring selection/grouping")
reaper.SetMouseModifier("Media item edge left drag", 7, "Stretch item ignoring snap and selection/grouping")
reaper.SetMouseModifier("Media item edge left drag", 8, "Move edge ignoring selection/grouping")
reaper.SetMouseModifier("Media item edge left drag", 9, "-1")
reaper.SetMouseModifier("Media item edge left drag", 10, "-1")
reaper.SetMouseModifier("Media item edge left drag", 11, "-1")
reaper.SetMouseModifier("Media item edge left drag", 12, "Stretch item ignoring selection/grouping")
reaper.SetMouseModifier("Media item edge left drag", 13, "-1")
reaper.SetMouseModifier("Media item edge left drag", 14, "Adjust loop section start/end")
reaper.SetMouseModifier("Media item edge left drag", 15, "-1")
